notepad/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

notes/urls.py
from .views import note_list_view, finished_item, delete_item, recover_item
from django.urls import path

urlpatterns = [
    path('',note_list_view, name = 'note-list' ),
    path('finish-item/<id>/',finished_item, name = 'finish-note-item'),
    path('delelte-item/<id>/',delete_item, name = 'delete-note-item'),
    path('recover-item/<id>/',recover_item, name = 'recover-note-item'),
    

]

notes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.

class Note(models.Model):
    LABEL_CHOICES = (
        ('P', 'primary'),
        ('SE', 'secondary'),
        ('S', 'success'),
        ('D', 'danger'),
        ('W', 'warning'),
        ('I', 'info'),
        ('L', 'light'),
        ('D', 'dark'),

    )

    title = models.CharField(max_length=100)
    due_date =  models.DateTimeField()
    label = models.CharField(choices=LABEL_CHOICES, max_length=2)
    finished = models.BooleanField(default=False)


    def __str__(self):
        return self.title

    def get_finish_url(self):
        return reverse('finish-note-item',kwargs={'id':self.id})

    def get_delete_url(self):
        return reverse('delete-note-item',kwargs={'id':self.id})

    def get_recover_url(self):
        return reverse('recover-note-item',kwargs={'id':self.id})

notes/forms.py
from django import forms
from .models import Note


class NoteModelForm(forms.ModelForm):
    
    class Meta:
        model = Note
        fields = ('title','due_date', 'label')

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Note
from .forms import NoteModelForm

# Create your views here.

def note_list_view(request):
    form = NoteModelForm()
    if request.method == 'POST':
        form = NoteModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('note-list')
    to_do_list = Note.objects.filter(finished=False)
    finished_list = Note.objects.filter(finished=True)
    context = {
        'to_do_list' : to_do_list ,
        'finished_list': finished_list,
        'form': form,
        }
    return render(request, 'note_list.html', context)


def finished_item(request, id):
    note = get_object_or_404(Note, id=id)
    note.finished = True
    note.save()

    return redirect('note-list')

def delete_item(request, id):
    note = get_object_or_404(Note, id=id)
    note.finished = True
    note.delete()

    return redirect('note-list')

def recover_item(request, id):
    note = get_object_or_404(Note, id=id)
    note.finished = False
    note.save()

    return redirect('note-list')

notes/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!-- font awesome link -->
    <script src="https://kit.fontawesome.com/2b9994a9c1.js" crossorigin="anonymous"></script>
    <title>Sumah's Todo App </title>


    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <!-- THIS LINE -->
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>


  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="container">

        
        {% block content %}
            
        {% endblock content %}
            
      
    </main><!-- /.container -->

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  </body>
</html>

notes/templates/note_list.html
{% extends 'base.html' %}

<style>
    .edit-from {
        margin-bottom: 10px;
    }
</style>
{% block content %}   
    <div class="text-center mt-5">
        <h2>To do List </h2> 
    </div>

    <hr>


    <div>
        <div>
            <h4>
                <a class="btn btn-primary" style="color: white;">
                        Create new Task <i class="fas fa-plus"></i>
                    </a>
            </h4>
                
            </div>
            <div>
                <div>
                    <form method='POST'>
                        {% csrf_token %}
                        <div class="form-group edit-from">
                            <label for="id_title">Title</label>
                            {{ form.title }}
                        </div>
                        <div class="form-group edit-from">
                            <label for="id_due_date">Due Date</label> 
                            {{ form.due_date }} <span>e.g 2008-08-20 02:00</span>
                        </div>
                        <div class="form-group edit-from">
                            <label for="id_label">Label</label>
                            {{ form.label }}
                          
                        </div>
                        <button type="submit" class="btn btn-primary">Create Task</button>
                      </form>
                </div>
            </div>
        </div>
    </div>


    
    <div class="row">
        {% for note in to_do_list %}

            {% include 'note_snippet.html'  with note_snippet_var=note type="DELETE" %}

        {% endfor %}
    </div>
    

    <div class="text-center mt-5">
        <h2>Finished List </h2> 
    </div>
    <hr>
    <div class="row">
        {% for note in finished_list %}

        {% include 'note_snippet.html'  with note_snippet_var=note type="ADD" %}

        {% endfor %}
    </div>

    {% endblock content %}
    
    
        

notes/templates/note_snippet.html
<style>
    h4 {
        position: relative;
    }

    .icons {
        position: absolute;
        right: 5px;
    }
</style>

<div class="card">
    <div class="card-body">
        <h4>{{ note_snippet_var.title }} 
            <span class="badge bg-{{ note_snippet_var.get_label_display }}">{{ note_snippet_var.due_date }}</span>
            <span class="icons" style="position: absolute; right: 5px;">
                
                {% if type == "DELETE" %}
                    <a href="{{ note_snippet_var.get_finish_url }}"><i class="fas fa-check"></i></a>
                {% else %}
                    <a href="{{ note_snippet_var.get_recover_url }}"><i class="fas fa-times"></i></a>
                {% endif %}
                    
                <a href="{{ note_snippet_var.get_delete_url }}" style="color: red;"><i class="fas fa-trash"></i></a>
            </span>
        </h4>
        
    </div>
</div>